// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9XoCjqNxo2L1DiuefsHYo_j1cZOyG-Z0',
    appId: '1:717007503209:web:b9993eb9b975f796a187f8',
    messagingSenderId: '717007503209',
    projectId: 'bunk-planer',
    authDomain: 'bunk-planer.firebaseapp.com',
    storageBucket: 'bunk-planer.appspot.com',
    measurementId: 'G-STB33E6XCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrqlDuwtGFn7LxE2DtygJxl1wzZwH6oww',
    appId: '1:717007503209:android:ab086c03cd2482bfa187f8',
    messagingSenderId: '717007503209',
    projectId: 'bunk-planer',
    storageBucket: 'bunk-planer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeT9djNWS3qW-HT_aXTYTPyXEXFc9I-tM',
    appId: '1:717007503209:ios:ac9eb7d3c84b840fa187f8',
    messagingSenderId: '717007503209',
    projectId: 'bunk-planer',
    storageBucket: 'bunk-planer.appspot.com',
    iosClientId: '717007503209-631krp7355mvcv4r2gbqm2minn9i1olu.apps.googleusercontent.com',
    iosBundleId: 'com.example.bunkPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeT9djNWS3qW-HT_aXTYTPyXEXFc9I-tM',
    appId: '1:717007503209:ios:ac9eb7d3c84b840fa187f8',
    messagingSenderId: '717007503209',
    projectId: 'bunk-planer',
    storageBucket: 'bunk-planer.appspot.com',
    iosClientId: '717007503209-631krp7355mvcv4r2gbqm2minn9i1olu.apps.googleusercontent.com',
    iosBundleId: 'com.example.bunkPlanner',
  );
}
